services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.pg1.address=:5432"
      # - "--entryPoints.pg2.address=:5433"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sulemanmahmood99@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      # - "5433:5433"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  raabta_backend:
    image: forge
    environment:
      APP_ENVIRONMENT: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raabta_backend.rule=Host(`admin.suleman.dev`)"
      - "traefik.http.routers.raabta_backend.entrypoints=websecure"
      - "traefik.http.routers.raabta_backend.tls.certresolver=myresolver"
      - "traefik.http.services.raabta_backend.loadbalancer.server.port=80"
    depends_on:
      - reverse-proxy

  raabta_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.raabta_postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.raabta_postgres.entrypoints=pg1"
      - "traefik.tcp.services.raabta_postgres.loadbalancer.server.port=5432"
    depends_on:
      - reverse-proxy

  smmac_force:
    image: force
    environment:
      APP_ENVIRONMENT: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smmac_force.rule=Host(`suleman.dev`)"
      - "traefik.http.routers.smmac_force.entrypoints=websecure"
      - "traefik.http.routers.smmac_force.tls.certresolver=myresolver"
      - "traefik.http.services.smmac_force.loadbalancer.server.port=80"
    depends_on:
      - reverse-proxy

  smmac_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smmac
    volumes:
      - smmac_pg_data:/var/lib/postgresql/data
      # labels:
      # - "traefik.enable=true"
      # - "traefik.tcp.routers.smmac_postgres.rule=HostSNI(`*`)"
      # - "traefik.tcp.routers.smmac_postgres.entrypoints=pg2"
      # - "traefik.tcp.services.smmac_postgres.loadbalancer.server.port=5433"
    depends_on:
      - reverse-proxy
    command:
      - "postgres"
      - "-p"
      - "5433"
      - "-c"
      - "shared_buffers=131072"
      - "-c"
      - "effective_cache_size=262144"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "log_min_duration_statement=1000"
    ports:
      - "5433:5433"

  # chrome:
  #   image: selenium/standalone-chrome:latest
  #   hostname: chrome
  #   privileged: true
  #   shm_size: 2g

volumes:
  raabta_pg_data:
  smmac_pg_data:
  letsencrypt:
